import type { PortfolioObjectConfig } from "@/lib/types";

export const portfolioObjects: PortfolioObjectConfig[] = [
  {
    slug: "panda-app",
    title: "PandA App",
    description: "Kyoto University LMS client application",
    targetType: "project",
    href: "/projects/panda-app",
    technologies: ["React Native", "Expo", "TypeScript"],
    position: [-2.4, 0, 0.3],
    sceneKind: "tower",
    githubUrl: "https://github.com/navyracooon/panda-app",
  },
  {
    slug: "portfolio",
    title: "Portfolio",
    description: "Personal portfolio built with Next.js and FastAPI",
    targetType: "project",
    href: "/projects/portfolio",
    technologies: ["Next.js", "FastAPI", "Three.js", "TypeScript"],
    position: [0, 0, 0],
    sceneKind: "tower",
    githubUrl: "https://github.com/navyracooon/portfolio",
  },
  {
    slug: "research",
    title: "Research",
    description: "Research activity and technical background",
    targetType: "project",
    href: "/projects/research",
    technologies: ["Python", "Optimization", "Control"],
    position: [2.4, 0, 0.25],
    sceneKind: "tower",
    githubUrl: "https://github.com/navyracooon/research-notes",
  },
  {
    slug: "dotfiles",
    title: "Dotfiles",
    description: "Terminal, editor, and shell setup for daily development",
    targetType: "project",
    href: "/projects/dotfiles",
    technologies: ["Neovim", "zsh", "tmux"],
    position: [-1.35, 0, -2.05],
    sceneKind: "house",
    githubUrl: "https://github.com/navyracooon/dotfiles",
  },
  {
    slug: "server-lab",
    title: "Server Lab",
    description: "Home server architecture, reverse proxy, and service separation",
    targetType: "project",
    href: "/projects/server-lab",
    technologies: ["Raspberry Pi", "Caddy", "Docker Compose"],
    position: [1.55, 0, -2.1],
    sceneKind: "rack",
    githubUrl: "https://github.com/navyracooon/portfolio",
  },
  {
    slug: "contact",
    title: "Contact",
    description: "Contact form",
    targetType: "contact",
    href: "/contact",
    technologies: ["FastAPI", "Validation"],
    position: [3.5, 0, -1.65],
    sceneKind: "sign",
  },
];
